/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterProviderRouteImport } from './routes/register-provider'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardPlansRouteImport } from './routes/_dashboard/plans'
import { Route as DashboardInvoicesRouteImport } from './routes/_dashboard/invoices'
import { Route as DashboardAdminRelationshipsRouteImport } from './routes/_dashboard/admin/relationships'
import { Route as DashboardAdminProvidersRouteImport } from './routes/_dashboard/admin/providers'
import { Route as DashboardAdminParticipantsRouteImport } from './routes/_dashboard/admin/participants'
import { Route as DashboardAdminInvitationsRouteImport } from './routes/_dashboard/admin/invitations'
import { Route as DashboardAdminCoordinatorsRouteImport } from './routes/_dashboard/admin/coordinators'
import { Route as DashboardAdminProvidersProviderIdRouteImport } from './routes/_dashboard/admin/providers.$providerId'
import { Route as DashboardAdminParticipantsParticipantIdRouteImport } from './routes/_dashboard/admin/participants.$participantId'
import { Route as DashboardAdminCoordinatorsCoordinatorIdRouteImport } from './routes/_dashboard/admin/coordinators.$coordinatorId'

const RegisterProviderRoute = RegisterProviderRouteImport.update({
  id: '/register-provider',
  path: '/register-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlansRoute = DashboardPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRelationshipsRoute =
  DashboardAdminRelationshipsRouteImport.update({
    id: '/admin/relationships',
    path: '/admin/relationships',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminProvidersRoute = DashboardAdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminParticipantsRoute =
  DashboardAdminParticipantsRouteImport.update({
    id: '/admin/participants',
    path: '/admin/participants',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminInvitationsRoute =
  DashboardAdminInvitationsRouteImport.update({
    id: '/admin/invitations',
    path: '/admin/invitations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminCoordinatorsRoute =
  DashboardAdminCoordinatorsRouteImport.update({
    id: '/admin/coordinators',
    path: '/admin/coordinators',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminProvidersProviderIdRoute =
  DashboardAdminProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => DashboardAdminProvidersRoute,
  } as any)
const DashboardAdminParticipantsParticipantIdRoute =
  DashboardAdminParticipantsParticipantIdRouteImport.update({
    id: '/$participantId',
    path: '/$participantId',
    getParentRoute: () => DashboardAdminParticipantsRoute,
  } as any)
const DashboardAdminCoordinatorsCoordinatorIdRoute =
  DashboardAdminCoordinatorsCoordinatorIdRouteImport.update({
    id: '/$coordinatorId',
    path: '/$coordinatorId',
    getParentRoute: () => DashboardAdminCoordinatorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-provider': typeof RegisterProviderRoute
  '/invoices': typeof DashboardInvoicesRoute
  '/plans': typeof DashboardPlansRoute
  '/': typeof DashboardIndexRoute
  '/admin/coordinators': typeof DashboardAdminCoordinatorsRouteWithChildren
  '/admin/invitations': typeof DashboardAdminInvitationsRoute
  '/admin/participants': typeof DashboardAdminParticipantsRouteWithChildren
  '/admin/providers': typeof DashboardAdminProvidersRouteWithChildren
  '/admin/relationships': typeof DashboardAdminRelationshipsRoute
  '/admin/coordinators/$coordinatorId': typeof DashboardAdminCoordinatorsCoordinatorIdRoute
  '/admin/participants/$participantId': typeof DashboardAdminParticipantsParticipantIdRoute
  '/admin/providers/$providerId': typeof DashboardAdminProvidersProviderIdRoute
}
export interface FileRoutesByTo {
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-provider': typeof RegisterProviderRoute
  '/invoices': typeof DashboardInvoicesRoute
  '/plans': typeof DashboardPlansRoute
  '/': typeof DashboardIndexRoute
  '/admin/coordinators': typeof DashboardAdminCoordinatorsRouteWithChildren
  '/admin/invitations': typeof DashboardAdminInvitationsRoute
  '/admin/participants': typeof DashboardAdminParticipantsRouteWithChildren
  '/admin/providers': typeof DashboardAdminProvidersRouteWithChildren
  '/admin/relationships': typeof DashboardAdminRelationshipsRoute
  '/admin/coordinators/$coordinatorId': typeof DashboardAdminCoordinatorsCoordinatorIdRoute
  '/admin/participants/$participantId': typeof DashboardAdminParticipantsParticipantIdRoute
  '/admin/providers/$providerId': typeof DashboardAdminProvidersProviderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/register-provider': typeof RegisterProviderRoute
  '/_dashboard/invoices': typeof DashboardInvoicesRoute
  '/_dashboard/plans': typeof DashboardPlansRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/admin/coordinators': typeof DashboardAdminCoordinatorsRouteWithChildren
  '/_dashboard/admin/invitations': typeof DashboardAdminInvitationsRoute
  '/_dashboard/admin/participants': typeof DashboardAdminParticipantsRouteWithChildren
  '/_dashboard/admin/providers': typeof DashboardAdminProvidersRouteWithChildren
  '/_dashboard/admin/relationships': typeof DashboardAdminRelationshipsRoute
  '/_dashboard/admin/coordinators/$coordinatorId': typeof DashboardAdminCoordinatorsCoordinatorIdRoute
  '/_dashboard/admin/participants/$participantId': typeof DashboardAdminParticipantsParticipantIdRoute
  '/_dashboard/admin/providers/$providerId': typeof DashboardAdminProvidersProviderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/invite'
    | '/login'
    | '/register'
    | '/register-provider'
    | '/invoices'
    | '/plans'
    | '/'
    | '/admin/coordinators'
    | '/admin/invitations'
    | '/admin/participants'
    | '/admin/providers'
    | '/admin/relationships'
    | '/admin/coordinators/$coordinatorId'
    | '/admin/participants/$participantId'
    | '/admin/providers/$providerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite'
    | '/login'
    | '/register'
    | '/register-provider'
    | '/invoices'
    | '/plans'
    | '/'
    | '/admin/coordinators'
    | '/admin/invitations'
    | '/admin/participants'
    | '/admin/providers'
    | '/admin/relationships'
    | '/admin/coordinators/$coordinatorId'
    | '/admin/participants/$participantId'
    | '/admin/providers/$providerId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/invite'
    | '/login'
    | '/register'
    | '/register-provider'
    | '/_dashboard/invoices'
    | '/_dashboard/plans'
    | '/_dashboard/'
    | '/_dashboard/admin/coordinators'
    | '/_dashboard/admin/invitations'
    | '/_dashboard/admin/participants'
    | '/_dashboard/admin/providers'
    | '/_dashboard/admin/relationships'
    | '/_dashboard/admin/coordinators/$coordinatorId'
    | '/_dashboard/admin/participants/$participantId'
    | '/_dashboard/admin/providers/$providerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RegisterProviderRoute: typeof RegisterProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-provider': {
      id: '/register-provider'
      path: '/register-provider'
      fullPath: '/register-provider'
      preLoaderRoute: typeof RegisterProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/plans': {
      id: '/_dashboard/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof DashboardPlansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/invoices': {
      id: '/_dashboard/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/relationships': {
      id: '/_dashboard/admin/relationships'
      path: '/admin/relationships'
      fullPath: '/admin/relationships'
      preLoaderRoute: typeof DashboardAdminRelationshipsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/providers': {
      id: '/_dashboard/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof DashboardAdminProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/participants': {
      id: '/_dashboard/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof DashboardAdminParticipantsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/invitations': {
      id: '/_dashboard/admin/invitations'
      path: '/admin/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof DashboardAdminInvitationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/coordinators': {
      id: '/_dashboard/admin/coordinators'
      path: '/admin/coordinators'
      fullPath: '/admin/coordinators'
      preLoaderRoute: typeof DashboardAdminCoordinatorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/providers/$providerId': {
      id: '/_dashboard/admin/providers/$providerId'
      path: '/$providerId'
      fullPath: '/admin/providers/$providerId'
      preLoaderRoute: typeof DashboardAdminProvidersProviderIdRouteImport
      parentRoute: typeof DashboardAdminProvidersRoute
    }
    '/_dashboard/admin/participants/$participantId': {
      id: '/_dashboard/admin/participants/$participantId'
      path: '/$participantId'
      fullPath: '/admin/participants/$participantId'
      preLoaderRoute: typeof DashboardAdminParticipantsParticipantIdRouteImport
      parentRoute: typeof DashboardAdminParticipantsRoute
    }
    '/_dashboard/admin/coordinators/$coordinatorId': {
      id: '/_dashboard/admin/coordinators/$coordinatorId'
      path: '/$coordinatorId'
      fullPath: '/admin/coordinators/$coordinatorId'
      preLoaderRoute: typeof DashboardAdminCoordinatorsCoordinatorIdRouteImport
      parentRoute: typeof DashboardAdminCoordinatorsRoute
    }
  }
}

interface DashboardAdminCoordinatorsRouteChildren {
  DashboardAdminCoordinatorsCoordinatorIdRoute: typeof DashboardAdminCoordinatorsCoordinatorIdRoute
}

const DashboardAdminCoordinatorsRouteChildren: DashboardAdminCoordinatorsRouteChildren =
  {
    DashboardAdminCoordinatorsCoordinatorIdRoute:
      DashboardAdminCoordinatorsCoordinatorIdRoute,
  }

const DashboardAdminCoordinatorsRouteWithChildren =
  DashboardAdminCoordinatorsRoute._addFileChildren(
    DashboardAdminCoordinatorsRouteChildren,
  )

interface DashboardAdminParticipantsRouteChildren {
  DashboardAdminParticipantsParticipantIdRoute: typeof DashboardAdminParticipantsParticipantIdRoute
}

const DashboardAdminParticipantsRouteChildren: DashboardAdminParticipantsRouteChildren =
  {
    DashboardAdminParticipantsParticipantIdRoute:
      DashboardAdminParticipantsParticipantIdRoute,
  }

const DashboardAdminParticipantsRouteWithChildren =
  DashboardAdminParticipantsRoute._addFileChildren(
    DashboardAdminParticipantsRouteChildren,
  )

interface DashboardAdminProvidersRouteChildren {
  DashboardAdminProvidersProviderIdRoute: typeof DashboardAdminProvidersProviderIdRoute
}

const DashboardAdminProvidersRouteChildren: DashboardAdminProvidersRouteChildren =
  {
    DashboardAdminProvidersProviderIdRoute:
      DashboardAdminProvidersProviderIdRoute,
  }

const DashboardAdminProvidersRouteWithChildren =
  DashboardAdminProvidersRoute._addFileChildren(
    DashboardAdminProvidersRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardPlansRoute: typeof DashboardPlansRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminCoordinatorsRoute: typeof DashboardAdminCoordinatorsRouteWithChildren
  DashboardAdminInvitationsRoute: typeof DashboardAdminInvitationsRoute
  DashboardAdminParticipantsRoute: typeof DashboardAdminParticipantsRouteWithChildren
  DashboardAdminProvidersRoute: typeof DashboardAdminProvidersRouteWithChildren
  DashboardAdminRelationshipsRoute: typeof DashboardAdminRelationshipsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardPlansRoute: DashboardPlansRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminCoordinatorsRoute: DashboardAdminCoordinatorsRouteWithChildren,
  DashboardAdminInvitationsRoute: DashboardAdminInvitationsRoute,
  DashboardAdminParticipantsRoute: DashboardAdminParticipantsRouteWithChildren,
  DashboardAdminProvidersRoute: DashboardAdminProvidersRouteWithChildren,
  DashboardAdminRelationshipsRoute: DashboardAdminRelationshipsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RegisterProviderRoute: RegisterProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
